In [1]:
import numpy as np

In [10]:
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [11]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#to print the data types of both the variables.

#Solution
"""
There is a difference in the data type of the list_ variable and the array_list variable. The elements in the
list_ variable are strings, while the elements in the array_list variable are converted to a common data type
by NumPy, which is likely integers.
"""
print("Data type of list",type(list_[0]))
print("Data types of array",array_list.dtype)

Data type of list <class 'str'>
Data types of array <U1


In [21]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and
#array_list.
print("Data Type of each element of list_")
for i in list_:
    print(type(i))
    
print("\nData Type of each element of array_list")
for i in array_list:
    print(type(i))

Data Type of each element of list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data Type of each element of array_list
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [19]:
#Q3. Considering the following changes in the variable, array_list:
array_list1 = np.array(object = list_, dtype = int)

In [20]:
#Will there be any difference in the data type of the elements present in both the variables, list_ and
#array_list1? If so then print the data types of each and every element present in both the variables, list_
#and arra_list.

#Solution
"""
There will be a difference in the data types of the elements present in the list_ variable and the array_list1 variable.
In the list_ variable, the elements are strings (e.g., '1', '2', etc.), while in the array_list1 variable, the elements
are integers.
"""
print("Data Type of each element of list_")
for i in list_:
    print(type(i))

print("\nData Type of each element of array_list1")
for i in array_list1:
    print(type(i))

Data Type of each element of list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data Type of each element of array_list1
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [22]:
#Consider the below code to answer further questions:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [25]:
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size

#Solution
print("Shape of num_array",num_array.shape)
print("Size of num_array",num_array.size)

Shape of num_array (2, 3)
Size of num_array 6


In [27]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#creation function.

#Solution
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?

#Solution
arr_i = np.identity((5))
print(arr_i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
